packages:
  - apps/*
  - packages/*
allowBuilds:
  "@sentry/cli": true
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
catalog:
  "@base-ui/react": ^1.3.0
  "@biomejs/biome": 2.3.10
  "@convex-dev/better-auth": ^0.11.4
  "@convex-dev/react-query": ^0.1.0
  "@cloudflare/vite-plugin": ^1.30.3
  "@databuddy/sdk": ^2.4.0
  "@effect/language-service": ^0.84.2
  "@fontsource-variable/geist": ^5.2.8
  "@openpanel/web": ^1.3.0
  "@phosphor-icons/react": ^2.1.10
  "@sentry/tanstackstart-react": ^10.47.0
  "@t3-oss/env-core": ^0.13.11
  "@tailwindcss/vite": ^4.2.2
  "@tanstack/react-form": ^1.28.6
  "@tanstack/react-query": ^5.96.1
  "@tanstack/react-router": ^1.168.10
  "@tanstack/react-router-devtools": ^1.166.11
  "@tanstack/react-router-ssr-query": ^1.166.10
  "@tanstack/react-router-with-query": ^1.130.17
  "@tanstack/react-start": ^1.167.16
  "@tanstack/router-plugin": ^1.167.12
  "@testing-library/dom": ^10.4.1
  "@testing-library/react": ^16.3.2
  "@types/node": ^25.5.0
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  "@unpic/react": ^1.0.2
  "@vitejs/plugin-react": ^6.0.1
  better-auth: 1.4.9
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  convex: ^1.34.1
  date-fns: ^4.1.0
  dotenv: ^17.3.1
  effect: ^3.21.0
  framer-motion: ^12.38.0
  jsdom: ^29.0.1
  next-themes: ^0.4.6
  nitro: 3.0.260311-beta
  react: 19.2.3
  react-day-picker: ^9.14.0
  react-dom: 19.2.3
  recharts: ^3.8.1
  shadcn: ^4.1.2
  sonner: ^2.0.7
  tailwind-merge: ^3.5.0
  tailwindcss: ^4.2.2
  tw-animate-css: ^1.4.0
  typescript: ^6.0.2
  ultracite: 6.5.1
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.15
  vite-tsconfig-paths: ^6.1.1
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  web-vitals: ^5.2.0
  wrangler: ^4.79.0
  zod: ^4.3.6

#catalogMode: prefer
#minimumReleaseAge: 1440
