packages:
  - apps/*
  - packages/*
allowBuilds:
  "@sentry/cli": true
catalog:
  "@convex-dev/better-auth": ^0.11.3
  "@effect/language-service": "^0.83.1"
  "@types/node": ^25.5.0
  better-auth: 1.4.9
  convex: ^1.34.0
  dotenv: ^17.3.1
  "effect": "^3.20.1"
  typescript: ^6.0.2
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.14
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  zod: ^4.3.6
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
