import '@/styles/globals.css';
import { ClientProvider } from '@/components/client-provider';
import { fontHeading, fontMono, fontSans } from '@/lib/fonts';
import { cn } from '@/lib/utils';
import { ReactNode } from 'react';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html
			lang='en'
			className={cn(
				'min-h-screen bg-background font-sans text-black',
				fontSans.variable,
				fontHeading.variable,
				fontMono.variable
			)}
		>
			<body className='antialiased'>
				<ClientProvider>{children}</ClientProvider>
			</body>
		</html>
	);
}
